export const SPACING = {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 28,
    xxxxl: 32,
    xxxxxl: 36,
    xxxxxxl: 40,
    xxxxxxxl: 44,
    xxxxxxxxl: 48,
    xxxxxxxxxl: 52,
    xxxxxxxxxxl: 56,
    xxxxxxxxxxxl: 60,
    xxxxxxxxxxxxl: 64,
    xxxxxxxxxxxxxl: 68,
    xxxxxxxxxxxxxxl: 72,
    xxxxxxxxxxxxxxxl: 76,
    xxxxxxxxxxxxxxxxl: 80,
    xxxxxxxxxxxxxxxxxl: 84,
    xxxxxxxxxxxxxxxxxxl: 88,
    xxxxxxxxxxxxxxxxxxxl: 92,
    xxxxxxxxxxxxxxxxxxxxl: 96,
    xxxxxxxxxxxxxxxxxxxxxl: 100,
};


